### ISSUE TITLE
Adicionar nome como colaborador

### ISSUE THREAD

**Issue by flaviovieira1** [flaviovieira1/GCMS-Flavio-Vieira#1]
[README](https://github.com/flaviovieira1/GCMS-Flavio-Vieira#readme)

**Comment by ramidedantas** [comment]
@flaviovieira1 Formate o Readme como está no meu repositório, incluindo seu nome, depois me marque aqui.

**Comment by flaviovieira1** [comment]
@ramidedantas Formatei

**Comment by ramidedantas** [comment]
Ok @flaviovieira1, nome adicionado, pode fechar issue.
